# Generated by Django 2.1.5 on 2019-01-18 06:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20190117_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color_identity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1, null=True), null=True, size=None),
        ),
    ]
