# Generated by Django 2.1.5 on 2019-01-18 06:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20190117_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5, null=True), size=None),
        ),
    ]
