# Generated by Django 2.1.5 on 2019-01-18 06:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20190117_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='variations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), null=True, size=None),
        ),
    ]
