# Generated by Django 2.1.5 on 2019-01-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20190117_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flavor',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
