# Generated by Django 2.1.5 on 2019-01-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20190117_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
