# Generated by Django 2.1.5 on 2019-01-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20190118_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='multiverse_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
