# Generated by Django 2.1.5 on 2019-01-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20190118_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='sdk_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
