# Generated by Django 2.1.5 on 2019-01-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20190118_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['id'], 'verbose_name': 'card', 'verbose_name_plural': 'cards'},
        ),
    ]
