# Generated by Django 2.1.5 on 2019-01-21 00:52

from django.db import migrations
from django.utils.text import slugify

def slugify_title_id(apps, schema_editor):
    Card = apps.get_model('db', 'Card')
    for card in Card.objects.all():
        card.slug = slugify(f'{card.id}-{card.name}')
        card.save()


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_card_slug'),
    ]

    operations = [
        migrations.RunPython(slugify_title_id,
            reverse_code=migrations.RunPython.noop),
    ]
