# Generated by Django 2.1.5 on 2019-01-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_auto_20190120_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
