# Generated by Django 2.1.5 on 2019-01-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_auto_20190124_1426'),
    ]

    operations = [
    ]
