# Generated by Django 2.1.5 on 2019-01-24 06:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0017_auto_20190120_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DeckCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
            ],
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['name'], 'verbose_name': 'card', 'verbose_name_plural': 'cards'},
        ),
        migrations.AddField(
            model_name='deckcards',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Card'),
        ),
        migrations.AddField(
            model_name='deckcards',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Deck'),
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(related_name='decks', through='db.DeckCards', to='db.Card'),
        ),
        migrations.AddField(
            model_name='collection',
            name='decks',
            field=models.ManyToManyField(related_name='collections', to='db.Deck'),
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
