# Generated by Django 2.1.5 on 2019-01-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_auto_20190124_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('name',), 'verbose_name': 'card', 'verbose_name_plural': 'cards'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('name',), 'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ('name',), 'verbose_name': 'deck', 'verbose_name_plural': 'decks'},
        ),
        migrations.AddField(
            model_name='collectioncards',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Card'),
        ),
        migrations.AddField(
            model_name='collectioncards',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Collection'),
        ),
        migrations.AddField(
            model_name='collection',
            name='cards',
            field=models.ManyToManyField(related_name='collections', through='db.CollectionCards', to='db.Card'),
        ),
        migrations.AlterUniqueTogether(
            name='collectioncards',
            unique_together={('collection', 'card')},
        ),
    ]
