# Generated by Django 2.1.5 on 2019-01-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_auto_20190124_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
