# Generated by Django 2.1.5 on 2019-01-29 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_auto_20190128_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectioncards',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectioncards', to='db.Card'),
        ),
        migrations.AlterField(
            model_name='collectioncards',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectioncards', to='db.Collection'),
        ),
        migrations.AlterField(
            model_name='deckcards',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deckcards', to='db.Card'),
        ),
        migrations.AlterField(
            model_name='deckcards',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deckcards', to='db.Deck'),
        ),
    ]
