# Generated by Django 2.1.5 on 2019-01-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_auto_20190124_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('name',), 'verbose_name': 'card', 'verbose_name_plural': 'cards'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('name',), 'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ('name',), 'verbose_name': 'deck', 'verbose_name_plural': 'decks'},
        ),
    ]
