# Generated by Django 2.1.5 on 2019-01-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_auto_20190128_1618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectionCards',
            new_name='CollectionCard',
        ),
    ]
