# Generated by Django 2.1.5 on 2019-02-01 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_auto_20190129_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='decks',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='collectioncard',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='collectioncard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='collectioncard',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionCard',
        ),
    ]
