# Generated by Django 2.1.5 on 2019-02-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_auto_20190131_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
        migrations.AlterUniqueTogether(
            name='deckcards',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='deckcards',
            name='card',
        ),
        migrations.RemoveField(
            model_name='deckcards',
            name='deck',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
        migrations.DeleteModel(
            name='DeckCards',
        ),
    ]
