# Generated by Django 2.1.5 on 2019-02-04 20:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_auto_20190131_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpansionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booster', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('border', models.CharField(max_length=10, null=True)),
                ('block', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('gatherer_code', models.CharField(max_length=10, null=True)),
                ('magic_cards_info_code', models.CharField(max_length=10, null=True)),
                ('mkm_id', models.CharField(max_length=10, null=True)),
                ('mkm_name', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=255)),
                ('old_code', models.CharField(max_length=10, null=True)),
                ('online_only', models.BooleanField(null=True)),
                ('release_date', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'set',
                'verbose_name_plural': 'sets',
                'ordering': ('release_date',),
            },
        ),
    ]
