# Generated by Django 2.1.5 on 2019-02-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_expansionset'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansionset',
            name='slug',
            field=models.SlugField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
