# Generated by Django 2.1.7 on 2019-02-16 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_auto_20190204_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpansionSetCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expansionsetcards', to='db.Card')),
                ('expansionset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expansionsetcards', to='db.ExpansionSet')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='expansionsetcard',
            unique_together={('card', 'expansionset')},
        ),
    ]
