# Generated by Django 2.1.7 on 2019-02-21 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_auto_20190221_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('name', 'release_date'), 'verbose_name': 'card', 'verbose_name_plural': 'cards'},
        ),
    ]
