# Generated by Django 2.1.5 on 2019-02-01 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0023_auto_20190131_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CollectionCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectioncards', to='db.Card')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectioncards', to='collection.Collection')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='cards',
            field=models.ManyToManyField(related_name='collections', through='collection.CollectionCard', to='db.Card'),
        ),
        migrations.AddField(
            model_name='collection',
            name='decks',
            field=models.ManyToManyField(related_name='collections', to='db.Deck'),
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='collectioncard',
            unique_together={('card', 'collection')},
        ),
    ]
