# Generated by Django 2.1.5 on 2019-02-03 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0024_auto_20190131_2246'),
        ('deck', '0001_initial'),
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiondeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectiondecks', to='deck.Deck'),
        ),
        migrations.AddField(
            model_name='collectioncard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectioncards', to='db.Card'),
        ),
        migrations.AddField(
            model_name='collectioncard',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectioncards', to='collection.Collection'),
        ),
        migrations.AddField(
            model_name='collection',
            name='cards',
            field=models.ManyToManyField(related_name='collections', through='collection.CollectionCard', to='db.Card'),
        ),
        migrations.AddField(
            model_name='collection',
            name='decks',
            field=models.ManyToManyField(related_name='collections', through='collection.CollectionDeck', to='deck.Deck'),
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='collectiondeck',
            unique_together={('collection', 'deck')},
        ),
        migrations.AlterUniqueTogether(
            name='collectioncard',
            unique_together={('card', 'collection')},
        ),
    ]
