# Generated by Django 2.1.5 on 2019-02-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_collection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncard',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
