# Generated by Django 2.1.5 on 2019-02-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
